spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}

futurekawa:
  mqtt:
    broker-url: tcp://localhost:1883
    client-id: fk-colombia-mqtt
    topic: sensors/#
